// Generated by CoffeeScript 2.7.0
var olog;

olog = function(obj) {
  return console.log(JSON.stringify(obj, null, 4));
};

//###########################################################
export var currentMRR = function(result) {
  var mrr, mrrDate;
  // olog result
  mrr = parseFloat(result.observations[0].value);
  mrrDate = new Date(result.observations[0].date);
  return {mrr, mrrDate};
};

//###########################################################
export var dataReleases = function(result) {
  var i, len, obj, ref, rel, releases;
  // olog result
  // date = result.realtime_start
  releases = [];
  ref = result.releases;
  for (i = 0, len = ref.length; i < len; i++) {
    rel = ref[i];
    obj = Object.create(null);
    obj.name = rel.name;
    obj.id = rel.id;
    obj.startDate = rel.realtime_start;
    obj.endDate = rel.realtime_end;
    releases.push(obj);
  }
  return releases;
};

export var releaseDates = function(result) {
  var i, len, rd, ref, releases;
  // olog result
  releases = [];
  ref = result.release_dates;
  for (i = 0, len = ref.length; i < len; i++) {
    rd = ref[i];
    releases.push(rd.date);
  }
  return releases;
};
