// Generated by CoffeeScript 2.7.0
var toYYYYMMDD;

import {
  request
} from "./throttledrequest.js";

import * as extr from "./dataextraction.js";

import * as urlCreate from "./urlcreate.js";

//###########################################################
toYYYYMMDD = function(date) {
  date = new Date(date);
  return date.toISOString().slice(0, 10);
};

//###########################################################
export var FRED = class FRED {
  constructor(key) {
    this.getCurrentMRR = this.getCurrentMRR.bind(this);
    this.getTodaysDataReleases = this.getTodaysDataReleases.bind(this);
    this.getDataReleasesForDate = this.getDataReleasesForDate.bind(this);
    this.getReleaseDatesForId = this.getReleaseDatesForId.bind(this);
    this.getFutureReleaseDatesForId = this.getFutureReleaseDatesForId.bind(this);
    this.key = key;
    this.req = request;
    this.minDate = "1990-01-01";
    this.maxDate = "9999-12-31";
  }

  async getCurrentMRR() {
    var result, url;
    url = urlCreate.latestMRR(this.key);
    result = (await this.req(url));
    return extr.currentMRR(result);
  }

  async getTodaysDataReleases() {
    var result, url;
    url = urlCreate.todaysDataReleases(this.key);
    result = (await this.req(url));
    return extr.dataReleases(result);
  }

  async getDataReleasesForDate(date) {
    var result, url;
    date = toYYYYMMDD(date);
    url = urlCreate.dataReleasesForDate(this.key, date);
    result = (await this.req(url));
    return extr.dataReleases(result);
  }

  async getReleaseDatesForId(id) {
    var result, url;
    url = urlCreate.releaseDatesForId(this.key, id, this.minDate, this.maxDate);
    result = (await this.req(url));
    return extr.releaseDates(result);
  }

  async getFutureReleaseDatesForId(id) {
    var result, startDate, url;
    startDate = toYYYYMMDD(new Date()); // start from today
    url = urlCreate.releaseDatesForId(this.key, id, startDate, this.maxDate);
    result = (await this.req(url));
    return extr.releaseDates(result);
  }

};
