// Generated by CoffeeScript 2.7.0
var maxPerWindow, pending, processQueue, processing, queue, waitMS, windowCount, windowMS, windowStart;

import {
  request as immediateRequest
} from "./request.js";

//###########################################################
//region Throttled Request Queue
// FRED API limit: 2 requests/second
// Strategy: allow bursts of 2, only wait if the burst was faster than 1s
// Deduplication: identical URL + options pairs are coalesced — fetched once, result shared
queue = [];

pending = new Map(); // key → {url, options, waiters: [{resolve, reject}, ...] }

processing = false;

windowStart = 0;

windowCount = 0;

maxPerWindow = 2;

windowMS = 1001; // 1s + 1ms safety margin


//###########################################################
waitMS = function(ms) {
  return new Promise(function(res) {
    return setTimeout(res, ms);
  });
};

//###########################################################
processQueue = async function() {
  var elapsed, err, i, j, key, len, len1, options, remaining, result, url, w, waiters;
  if (processing || queue.length === 0) { //# Queue is empty or active
    return;
  }
  processing = true; // set queu active
  while (queue.length > 0) {
    // Start new measurement window
    if (windowCount === 0) {
      windowStart = performance.now();
    }
    windowCount++;
    key = queue.shift();
    ({url, options, waiters} = pending.get(key));
    try {
      result = (await immediateRequest(url, options));
      pending.delete(key);
      for (i = 0, len = waiters.length; i < len; i++) {
        w = waiters[i];
        w.resolve(result);
      }
    } catch (error) {
      err = error;
      pending.delete(key);
      for (j = 0, len1 = waiters.length; j < len1; j++) {
        w = waiters[j];
        w.reject(err);
      }
    }
    // After max requests, check if we need to slow down
    if (windowCount >= maxPerWindow) {
      elapsed = performance.now() - windowStart;
      remaining = windowMS - elapsed;
      if (remaining > 0) {
        await waitMS(remaining);
      }
      windowCount = 0;
    }
  }
  processing = false;
  processQueue();
};

//###########################################################
export var request = function(url, options = {}) { // rate limited request
  var err, key, prom, promFun;
  try {
    // Deduplicating requests - sensitive to differing options
    key = url + JSON.stringify(options);
  } catch (error) {
    err = error;
    throw new Error("corrupted options passed!");
  }
  // Notice: if two options objects are mutations in prop orders 
  //    even when the content is the same 
  //    it is still causing a separated request
  //    While this is suboptimal, it is very rare, causes no harm
  //    and no worthy solution was found yet
  promFun = function(resolve, reject) {
    if (pending.has(key)) {
      pending.get(key).waiters.push({resolve, reject});
      return;
    }
    pending.set(key, {
      url,
      options,
      waiters: [{resolve, reject}]
    });
    queue.push(key);
  };
  prom = new Promise(promFun);
  if (!processing) {
    processQueue();
  }
  return prom;
};

//endregion
